# Local kernel config overlay for GitHub Actions runner quirks, if we find any

include "arch/amd64/conf/MICROVM"

#ident		"FIRECRACKER-$Revision$"

no config	netbsd
config		netbsd	root on ld0a type ffs
