# Local kernel config overlay for GitHub Actions runner quirks, if we find any

include "arch/amd64/conf/MICROVM"

#ident		"FIRECRACKER-$Revision$"

# Examples of the kind of overrides that could be used:
#options 	CONSDEVNAME="\"com\"",CONADDR=0x3f8,CONSPEED=115200
#no options 	SOMETHING_THAT_BREAKS_ON_GHA
