rc_configured=YES

hostname=netbsd-firecracker

fcnet=YES
dhcpcd=NO

sshd=YES

resize_root=YES
resize_root_postcmd="/sbin/reboot -n"

wscons=NO
makemandb=NO
savecore=NO
virecover=NO
postfix=NO
cron=NO
